name: PQC

on:
  - push
  - pull_request

jobs:
  unit-test:
    name: Unit tests
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
      - name: run tests
        run: |
          cd build && ./ut
      - name: Build Rust bindings
        run: |
          cd src/rustapi/pqc-sys && cargo build
      - name: Run KAT tests
        run: |
          cd test/katrunner &&
          curl http://amongbytes.com/~flowher/permalinks/kat.zip --output kat.zip
          unzip kat.zip
          cargo run --release -- --katdir KAT
